# PEOPLE schema

# --- !Ups
CREATE TABLE TBL_PEOPLE (
  DOCUMENT varchar(10) NOT NULL,
  NAME varchar(20) NOT NULL,
  LAST_NAME varchar(20) NOT NULL,
  CONSTRAINT PEOPLE_PK PRIMARY KEY (DOCUMENT)
);

# --- !Downs
DROP TABLE TBL_PEOPLE;